Ft enable social login #147322191
andela/wger_yosemite pull request #10
Opened 2017-07-05 15:20 UTC by daisymacharia

#### What does this PR do?
Enable social login.

#### Description of Task to be completed?
The user will be able to login using face book, google or twitter.

#### How should this be manually tested?
The user could try manually login in using their social media account.

#### Screenshots (if appropriate)
<img width="959" alt="screen shot 2017-07-05 at 18 17 17" src="https://user-images.githubusercontent.com/28440972/27871444-55450e04-61ae-11e7-8c5d-5aedfe02ae51.png">
<img width="500" alt="screen shot 2017-07-05 at 18 20 31" src="https://user-images.githubusercontent.com/28440972/27871559-abc544ba-61ae-11e7-8e89-1bebf4697e1c.png">

2017-07-05 17:53 UTC, egichuri requested changes
Awesome work @daisymacharia 
Please work on the comments.

2017-07-05 17:53 UTC, egichuri commented on requirements_devel.txt
> +alabaster==0.7.10
There seems to be quite a number of packages not related to this task. please clean this up

2017-07-05 17:53 UTC, egichuri commented on wger/settings_global.py
> +# facebook, twitter and google API keys
Would be better to use env variables for this.

2017-07-05 17:53 UTC, egichuri commented on wger/settings_global.py
> +# facebook, twitter and google API keys
For clarity... any sensitive information that our app needs should not be made public. While changing this please also use env variables for the secret key

2017-07-05 17:54 UTC, egichuri commented on requirements_devel.txt
> +alabaster==0.7.10
on second thought.. i'm merging a branch with the cleaned up requirements. you can update your branch with develop once that's done

2017-07-05 20:10 UTC, daisymacharia commented on requirements_devel.txt
> +alabaster==0.7.10
okay lemme work on that

2017-07-05 20:11 UTC, daisymacharia commented on wger/settings_global.py
> +# facebook, twitter and google API keys
okay i'll change that

2017-07-07 09:05 UTC, egichuri commented
@daisymacharia just noticed a couple more places where we need to add the social login buttons. Let's pair on this on monday.

2017-07-07 13:45 UTC, merged