Ft cache nutrition values #147322155
andela/wger_yosemite pull request #19
Opened 2017-07-12 10:03 UTC by daumie

## What does this PR do?
> Cache nutritional values therefore increasing render time

## Description of task to be completed
If a user has many plans (approx. more than 25), the overview renders slowly as too many DB-queries are fired just to calculate the total calories. Some caching of the values is probably the easiest solution, similar to the canonical_representation for workouts.

### Relevant pivotal tracker stories
#147322155

2017-07-12 13:13 UTC, egichuri requested changes

2017-07-12 13:13 UTC, egichuri commented on wger/nutrition/views/plan.py
>      template_data['plans'] = plans
seems like the looping doesn't change the data we're sending to the template. we're still using `plans`.

2017-07-12 13:13 UTC, egichuri commented on wger/nutrition/views/plan.py
> +        cache_value = cache.get(cache_mapper.get_nutrition_plan(int(plan.id)))
does this just set the cache? or is the data cached used in the template?

2017-07-14 09:50 UTC, daumie commented on wger/nutrition/views/plan.py
> +        cache_value = cache.get(cache_mapper.get_nutrition_plan(int(plan.id)))
This sets the cache

2017-07-18 08:12 UTC, egichuri approved these changes

2017-07-18 08:12 UTC, merged