Improves Travis Efficiency by trimming some Builds  #148105193
andela/wger_yosemite pull request #9
Opened 2017-07-03 13:21 UTC by daumie

### What does this PR do?
Improves Travis CI Efficiency

###Description of tasks completed.
Have Travis CI build time decreased by removing some versions
of python and development database

### What are the relevant pivotal tracker stories?
 #148105193

2017-07-03 20:37 UTC, egichuri requested changes

2017-07-03 20:37 UTC, egichuri commented on wger/settings_global.py
> +# DATABASES = {'default': dj_database_url.config(default=os.environ["DATABASE_URL"])}
we need this db configuration for the sake of heroku

2017-07-03 20:37 UTC, egichuri commented on .travis.yml
> +  - pip install -r requirements.txt
any reason why this was changed from `requirements_devel.txt`? It's importing `requirements.txt` so just ensure no packages are repeated in both.

2017-07-05 18:39 UTC, merged

2017-07-06 06:52 UTC, daumie reviewed
I have removed repeated packages from **requirements.txt**. 
Re-added the **heroku db** configuration.
I will need help fixing the failing

2017-07-06 06:52 UTC, daumie commented on wger/settings_global.py
> +# DATABASES = {'default': dj_database_url.config(default=os.environ["DATABASE_URL"])}
I will have this corrected, this means the build failure has something to do with this. Any ideas of possible workarounds?

2017-07-06 06:55 UTC, egichuri commented
This has already been merged